[dimensions]
cols = 15
rows = 20
tileSize = 32

[geometry]
core = [ 6, 10 ]
nests = [ [ 0, 0 ], [ 14, 0 ] ]

[meta]
description = 'The intersection'
name = 'Intersection'

[[tiles]]
buildable = false
type = 'Nest'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Nest'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
mul = false
statKey = 'range'
type = 'Buff'
value = 30.0
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
mul = false
statKey = 'range'
type = 'Buff'
value = 30.0
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Core'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
mul = true
statKey = 'shotsPerMinute'
type = 'Buff'
value = 1.5
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = false
type = 'Rock'
walkable = false

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
mul = true
statKey = 'damage'
type = 'Buff'
value = 1.5
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true

[[tiles]]
buildable = true
type = 'Grass'
walkable = true
